# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.0

    steps:
      - checkout

      - run: go build cmd/service/main.go
      - run: go test -v ./...